apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: ashimshrestha/simple
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
